INSERT INTO ofertas.areas_conocimiento(id_aut_areaconocimiento, nombre)
VALUES
(1, 'Administrativo'),
(2, 'Agronomía'),
(3, 'Alimentos y bebidas'),
(4, 'Almacén'),
(5, 'Archivo'),
(6, 'Arquitectura'),
(7, 'Aseguramiento de la calidad'),
(8, 'Asesorías'),
(9, 'Auditoría'),
(10, 'Automatización/Instrumentación'),
(11, 'Bacteriología'),
(12, 'Banca Corporativa'),
(13, 'Banca Personal'),
(14, 'Bienestar'),
(15, 'Bodega'),
(16, 'Capacitación'),
(17, 'Cartera'),
(18, 'Comercial'),
(19, 'Comercio Exterior'),
(20, 'Compensación y Pagos'),
(21, 'Compras'),
(22, 'Comunicaciones'),
(23, 'Construcción y Obra'),
(24, 'Consumo Masivo'),
(25, 'Contabilidad'),
(26, 'Contratos'),
(27, 'Cooperativa/Fondo de Empleados'),
(28, 'Costos y Presupuestos'),
(29, 'Crédito y cobranza'),
(30, 'Desarrollo'),
(31, 'Dibujo'),
(32, 'Diseño'),
(33, 'Diseño textil'),
(34, 'Diseño y construcción'),
(35, 'Diseño y Montaje'),
(36, 'Diseño y Publicidad'),
(37, 'Distribución'),
(38, 'Docencia'),
(39, 'Edición'),
(40, 'Exportación'),
(41, 'Facturación'),
(42, 'Financiera'),
(43, 'Gerencia'),
(44, 'Hidráulica'),
(45, 'Hospitalización'),
(46, 'Hotelería y Turismo'),
(47, 'Importaciones'),
(48, 'Ingeniería'),
(49, 'Interventoría'),
(50, 'Inversiones'),
(51, 'Investigación'),
(52, 'Jurídica'),
(53, 'Licitaciones'),
(54, 'Logística'),
(55, 'Mantenimiento'),
(56, 'Mercadeo'),
(57, 'Mercadeo Internacional'),
(58, 'Odontología'),
(59, 'Operaciones'),
(60, 'Otras'),
(61, 'Planeación/Proyectos'),
(62, 'Planificación'),
(63, 'Producción'),
(64, 'Psicología'),
(65, 'Publicidad'),
(66, 'Recreación y Deporte'),
(67, 'Recursos Humanos'),
(68, 'Relaciones Publicas/Eventos'),
(69, 'Salud'),
(70, 'Seguridad Industrial y Riesgos'),
(71, 'Seguros'),
(72, 'Servicio al Cliente'),
(73, 'Servicios Generales'),
(74, 'Sistemas/Informática'),
(75, 'Técnico'),
(76, 'Tecnología'),
(77, 'Telecomunicaciones'),
(78, 'Telemercadeo'),
(79, 'Tesorería'),
(80, 'Trabajo Social'),
(81, 'Trade Marketing'),
(82, 'Transporte'),
(83, 'Ventas');