INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(1,'Abogado(a) Independiente',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(2,'Abogado(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(3,'Actor/Actriz',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(4,'Administrador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(5,'Administrativo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(6,'Agente',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(7,'Almacenista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(8,'Ama de llaves',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(9,'Analista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(10,'Animador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(11,'Archivador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(12,'Arquitecto(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(13,'Arreglista Musical',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(14,'Artista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(15,'Asesor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(16,'Asistente',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(17,'Asistente de investigacion',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(18,'Asociado(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(19,'Atrilero',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(20,'Auditor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(21,'Auxiliar',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(22,'Auxiliar de vuelo',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(23,'Azafata',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(24,'Bactereólogo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(25,'Bioanalista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(26,'Bombero(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(27,'Cajero(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(28,'Caligrafo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(29,'Camarero(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(30,'Camarografo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(31,'Capacitador',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(32,'Capellán',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(33,'Capitán',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(34,'Cartógrafo',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(35,'Chef',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(36,'Científico(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(37,'Citotecnólogo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(38,'Cobrador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(39,'Comandante',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(40,'Comprador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(41,'Comunicador(a) Social',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(42,'Concertino',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(43,'Conductor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(44,'Consultor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(45,'Contador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(46,'Contralor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(47,'Coordinador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(48,'Corredor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(49,'Cuñero',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(50,'Curador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(51,'Decano(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(52,'Despachador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(53,'Diagramador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(54,'Dibujante',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(55,'Dibujante Ilustrador',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(56,'Dietista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(57,'Director(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(58,'Director(a) de Área',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(59,'Director(a) de Division',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(60,'Director(a) Ejecutivo',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(61,'Director(a) General',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(62,'Diseñador(a) Grafico(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(63,'Diseñador Curricular',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(64,'Diseñador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(65,'Docente-Profesor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(66,'Economista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(67,'Ecónomo',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(68,'Editor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(69,'Ejecutivo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(70,'Ejecutivo(a) Junior',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(71,'Ejecutivo(a) Senior',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(72,'Encargado(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(73,'Encuellador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(74,'Encuestador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(75,'Enfermero(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(76,'Entrenador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(77,'Estilista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(78,'Estilista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(79,'Estudiante',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(80,'Estudiante de Posgrado',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(81,'Estudiante para Tesis',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(82,'Facilitador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(83,'Farmacéutico(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(84,'Fisioterapeuta',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(85,'Fonoaudiólogo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(86,'Fotógrafo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(87,'Fotolitógrafo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(88,'Geofísico(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(89,'Geólogo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(90,'Gerente',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(91,'Gerente General',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(92,'Guía',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(93,'Guionista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(94,'Hostess',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(95,'Ilustrador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(96,'Impulsador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(97,'Ingeniero(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(98,'Inspector(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(99,'Instalador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(100,'Instructor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(101,'Instrumentador(a) Quirúrgico',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(102,'Interventor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(103,'Investigador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(104,'Jefe',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(105,'Kinesiólogo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(106,'Libretista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(107,'Líder de Proyecto',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(108,'Locutor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(109,'Luminotecnico(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(110,'Maitress',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(111,'Manicurista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(112,'Maquetista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(113,'Mecánico(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(114,'Mecánico Dental',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(115,'Medico(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(116,'Medico(a) Especialista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(117,'Mensajero(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(118,'Mercaderista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(119,'Mesero(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(120,'Miembro de Junta Directiva',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(121,'Modista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(122,'Niñero(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(123,'Notario(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(124,'Odontólogo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(125,'Oficinista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(126,'Operador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(127,'Operario(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(128,'Orientador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(129,'Otro Profesional',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(130,'Periodista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(131,'Planeador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(132,'Planificador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(133,'Practicante',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(134,'Preparador de alimentos',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(135,'Presidente(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(136,'Productor',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(137,'Profesional',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(138,'Programador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(139,'Promotor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(140,'Propietario(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(141,'Psicólogo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(142,'Psicopedagogo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(143,'Publicista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(144,'Químico(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(145,'Realizador',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(146,'Recepcionista',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(147,'Rector(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(148,'Redactor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(149,'Reportero(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(150,'Representante',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(151,'Representante de ventas',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(152,'Residente',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(153,'Revisor(a) Fiscal',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(154,'Secretario(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(155,'Secretario(a) Berlingue',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(156,'Secretario(a) General',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(157,'Socio(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(158,'Subdirector(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(159,'Subdirector(a) General',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(160,'Subgerente',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(161,'Supernumerario(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(162,'Supervisor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(163,'Técnico(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(164,'Técnico(a) Superior',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(165,'Teleoperador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(166,'Tesorero(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(167,'Topógrafo(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(168,'Trabajador(a) Social',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(169,'Trader',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(170,'Traductor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(171,'Vendedor(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(172,'Vicepresidente(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(173,'Vicerector(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(174,'Vigilante',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(175,'Visitador(a) Medico(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(176,'Webmaster/Desarrollador(a)',true);
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(177,'Zootecnista',true);


--
-- CARGOS PARA OFERTAS LABORALES
--
INSERT INTO ofertas.cargos(id_aut_cargos, nombre, estado) values(278,'Administrador Base de Datos',true);
COMMIT;