INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(1,'Agropecuario');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(2,'Alimentos');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(3,'Asegurador');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(4,'Bebidas y Tabaco');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(5,'Comercial');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(6,'Comercio al por Mayor');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(7,'Comercio al por Menor');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(8,'Construcción');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(9,'Consultorías/Asesorías');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(10,'Consumo Masivo');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(11,'Cuero y Calzado');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(12,'Editorial e Impresión');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(13,'Educativo');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(14,'Energético');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(15,'Entretenimiento');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(16,'Estatal y Relacionados');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(17,'Financiero');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(18,'Industrial');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(19,'Investigación');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(20,'Manufactura');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(21,'Medios');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(22,'Minería, Hierro, Acero y otros Materiales');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(23,'Naval');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(24,'Otra Actividad');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(25,'Plástico y Caucho');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(26,'Productos de Vidrio');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(27,'Publicidad y Mercadeo');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(28,'Pulpa, Papel y Cartón');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(29,'Químicos');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(30,'Salud');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(31,'Servicios');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(32,'Tecnología');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(33,'Telecomunicaciones');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(34,'Textiles, Prendas de Vestir y Calzado');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(35,'Transporte');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(36,'Vehículos y Partes');


COMMIT;

INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(1,'Agricultura y Varios',1);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(2,'Avícola',1);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(3,'Café Producción',1);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(4,'Distribución de Productos',1);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(5,'Flores',1);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(6,'Ganadería',1);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(7,'Pesca',1);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(8,'Aceites y Grasas Comestibles',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(9,'Alimentos Para Animales',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(10,'Azúcar',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(11,'Batidos',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(12,'Café Exportadores',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(13,'Chocolate y Confitería',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(14,'Conservas, Pasabocas',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(15,'Lácteos',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(16,'Molinera de Arroz',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(17,'Molinería de Productos de Trigo',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(18,'Pastas, Panadería y Galletas',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(19,'Productos Cárnicos',2);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(20,'Ajustadores de Seguros',3);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(21,'Compañías de Seguros',3);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(22,'Corredores de Seguros',3);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(23,'Reaseguradores',3);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(24,'Cerveza',4);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(25,'Distribución/Consumo Masivo',4);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(26,'Gaseosas, Jugos y Agua',4);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(27,'Licores',4);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(28,'Tabaco',4);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(29,'Comercio',5);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(30,'Comercio al por Mayor',6);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(31,'Almacenes de Cadena',7);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(32,'Almacenes Varios',7);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(33,'Concesionarios',7);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(34,'Droguerías',7);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(35,'Estaciones de Servicio',7);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(36,'Ferretería',7);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(37,'Hipermercados',7);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(38,'Supermercados',7);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(39,'Tiendas',7);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(40,'Acondicionamiento',8);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(41,'Cementos',8);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(42,'Cerámica y otros Materiales',8);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(43,'Construcción',8);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(44,'Distribución de Materiales',8);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(45,'Infraestructura',8);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(46,'Infraestructura Víal',8);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(47,'Ingeniería Civil',8);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(48,'Preparación de Terreno',8);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(49,'Vivienda',8);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(50,'Consultoría Contable',9);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(51,'Consultoría de Recursos Humanos',9);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(52,'Firmas de Abogados',9);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(53,'Firmas de Consultoría Empresarial',9);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(54,'Temporales/Dotación',9);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(55,'Consumo Masivo',10);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(56,'Calzado',11);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(57,'Curtido de Cuero',11);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(58,'Maletas, Bolsos y Similares',11);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(59,'Impresión Editorial',12);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(60,'Libros, Folletos y Similares',12);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(61,'Campañas de Capacitación',13);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(62,'Colegios',13);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(63,'Institutos Técnicos',13);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(64,'Universidades',13);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(65,'Compañías Petroleras',14);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(66,'Distribución de Carbón',14);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(67,'Distribución de Combustibles',14);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(68,'Energía Eléctrica',14);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(69,'Gas',14);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(70,'Servicios Petroleros',14);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(71,'Cine y Videos',15);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(72,'Otros',15);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(73,'Parques de Diversiones',15);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(74,'Producción de Grabación',15);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(75,'Agricultura y Desarrollo',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(76,'Ciencia y Tecnología',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(77,'Comercio Exterior',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(78,'Comunicación',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(79,'Defensa y Seguridad Nacional',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(80,'Economía y Desarrollo Ecológico',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(81,'Educación, Cultura y Turismo',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(82,'Estadística',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(83,'Función Pública',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(84,'Gremios y Asociaciones',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(85,'Interior, Control y org',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(86,'Justicia del Derecho',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(87,'Medio Ambiente',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(88,'Minas y Energía',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(89,'Organización no Gubernamental',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(90,'Planeación',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(91,'Relaciones Exteriores',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(92,'Residencia, Gobernaciones',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(93,'Salud, Trabajo y Seguridad',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(94,'Servicios Públicos',16);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(95,'Banca',17);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(96,'Cajeros Electrónicos',17);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(97,'Compañías de Financiamiento',17);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(98,'Compañías de Leasing',17);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(99,'Corporaciones de Ahorro',17);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(100,'Corredores de Bolsa',17);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(101,'Fiduciaria',17);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(102,'Fondo de Pensiones',17);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(103,'Servicios Financieros',17);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(104,'Tarjeta de Crédito',17);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(105,'Varios',18);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(106,'Varios',19);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(107,'Distribución de Enseres Domiciliários',20);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(108,'Distribución de Maquinaria',20);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(109,'Electrodomésticos',20);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(110,'Manufacturas Varias',20);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(111,'Maquinaria y Equipo',20);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(112,'Muebles y Accesorios',20);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(113,'Productos de Madera',20);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(114,'Internet',21);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(115,'Periódicos',21);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(116,'Radio',21);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(117,'Revistas',21);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(118,'Televisión',21);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(119,'Metales Básicos, Hierro, Acero',22);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(120,'Metales no Ferrosos',22);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(121,'Otros',22);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(122,'Productos de Metal',22);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(123,'Siderurgia',22);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(124,'Construcción Naval',23);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(125,'Diseño Naval',23);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(126,'Mantenimiento Naval',23);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(127,'Naval',23);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(128,'Reparación Naval',23);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(129,'Atelier de Diseño',24);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(130,'Otra Actividad',24);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(131,'Plásticos Primarios',25);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(132,'Productos de Caucho',25);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(133,'Productos de Plástico',25);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(134,'Envases',26);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(135,'Otros Productos de Vidrio',26);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(136,'Vidrio - Construcción',26);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(137,'Vidrio - Vehículo',26);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(138,'Agencias de Publicidad',27);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(139,'Agencias Promocionales',27);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(140,'Brockers de Medios',27);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(141,'Correo Directo',27);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(142,'Otros',27);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(143,'Relaciones Públicas',27);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(144,'Papel, Celulosa y Cartón',28);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(145,'Productos de Papel y Cartón',28);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(146,'Abonos, Plaguicidas y Químicos',29);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(147,'Distribución/Consumo Masivo',29);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(148,'Distribución de Productos',29);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(149,'Laboratorios Farmacéuticos',29);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(150,'Pinturas, Barnices y Similares',29);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(151,'Productos de Aseo y Cosméticos',29);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(152,'Químicos Básicos',29);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(153,'Químicos Industriales',29);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(154,'A.R.P',30);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(155,'E.P.S',30);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(156,'I.P.S',30);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(157,'Medicina Prepagada',30);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(158,'Seguridad Social',30);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(159,'Servicios Hospitalarios',30);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(160,'Alimentos - Bebidas',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(161,'Almacenes de Depósito',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(162,'Cajas de Compensación',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(163,'Clubes',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(164,'Cooperativas',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(165,'Correo',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(166,'Hoteles',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(167,'Informáticos',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(168,'Otros Servicios',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(169,'Restaurantes',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(170,'Servicios de Aseo',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(171,'Servicios Públicos',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(172,'Turismo',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(173,'Vigilancia y Seguridad',31);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(174,'Comercio de Computadores',32);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(175,'Desarrollo y Diseño de Páginas Web',32);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(176,'Productores y Distribuidores',32);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(177,'Celulares',33);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(178,'Equipos de Comunicación',33);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(179,'Otros',33);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(180,'Servicios de Comunicación',33);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(181,'Acabados Textiles',34);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(182,'Confecciones',34);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(183,'Distribución de Productos',34);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(184,'Hilanderas',34);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(185,'Textiles',34);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(186,'Aéreo',35);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(187,'Agente',35);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(188,'Marítimo y Fluvial',35);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(189,'Operadores, Agentes y Terminales',35);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(190,'Valores',35);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(191,'Academia Automovilística',36);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(192,'Carrocerías, Partes y Piezas',36);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(193,'Comercialización',36);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(194,'Concesionarios',36);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(195,'Ensambladoras de Vehículos',36);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(196,'Importadores de Vehículos',36);
INSERT INTO ofertas.sub_sectores(id_aut_sub_sector, nombre,id_sectores) values(197,'Talleres',36);

COMMIT;