INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (1,'Sede Popayán',2,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (2,'Sede Norte',3,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (3,'Sede Piendamó',1,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (4,'Sede Guapi',1,);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (5,'Sede Miranda',1,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (6,'Sede Bolívar'1,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (7,'Sede El Bordo'1,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (8,'Sede Silvia',1,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (9,'Sede Pasto - Universidad de Nariño',1,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (10,'Sede Cali - Universidad de San Buenaventura'1,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (11,'Sede Cartagena - Escuela Naval Almirante Padilla'1,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (12,'Sede Bogotá - Universidad EAN',1,1);
INSERT INTO  ofertas.sede(id_aut_sede,nombre,id_localizacion,id_universidad) VALUES (13,'Sede Bogotá - Universidad El Bosque',1,1);