INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (1,'MAESTRO EN CLARINETE');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (2,'MAESTRO EN VIOLÍN');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (3,'MAESTRO EN PERCUSIÓN');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (4,'MAESTRO EN SAXOFÓN');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (5,'MAESTRO EN TROMPETA');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (6,'MAESTRO EN GUITARRA');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (7,'MAESTRO EN TROMBÓN');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (8,'MAESTRO EN CANTANTE LÍRICO');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (9,'MAESTRO EN TUBA');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (10,'MAESTRO EN EUFONIO');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (11,'MAESTRO EN CORNO');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (12,'MAESTRO EN FAGOT');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (13,'MAESTRO EN FLAUTA');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (14,'MAESTRO EN FLAUTA TRAVERSA');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (15,'MAESTRO EN PIANO');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (16,'MAESTRO EN CONTRABAJO');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (17,'MAESTRO EN VIOLA');
INSERT INTO  ofertas.titulo(id_aut_titulo,nombre) VALUES (18,'MAESTRO EN VIOLONCHELO');
 
 COMMIT;