--Paises
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (1,'Afghanistan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (2,'Albania');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (3,'Algeria');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (4,'American Samoa');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (5,'Andorra');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (6,'Angola');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (7,'Anguilla');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (8,'Antarctica');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (9,'Antigua And Barbuda');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (10,'Argentina');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (11,'Armenia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (12,'Aruba');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (13,'Australia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (14,'Austria');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (15,'Azerbaijan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (16,'Bahamas The');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (17,'Bahrain');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (18,'Bangladesh');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (19,'Barbados');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (20,'Belarus');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (21,'Belgium');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (22,'Belize');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (23,'Benin');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (24,'Bermuda');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (25,'Bhutan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (26,'Bolivia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (27,'Bosnia and Herzegovina');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (28,'Botswana');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (29,'Bouvet Island');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (30,'Brazil');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (31,'British Indian Ocean Territory');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (32,'Brunei');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (33,'Bulgaria');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (34,'Burkina Faso');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (35,'Burundi');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (36,'Cambodia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (37,'Cameroon');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (38,'Canada');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (39,'Cape Verde');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (40,'Cayman Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (41,'Central African Republic');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (42,'Chad');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (43,'Chile');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (44,'China');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (45,'Christmas Island');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (46,'Cocos(Keeling) Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (47,'Colombia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (48,'Comoros');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (49,'Republic Of The Congo');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (50,'Democratic Republic Of The Congo');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (51,'Cook Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (52,'Costa Rica');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (53,'Cote Ivoire(Ivory Coast)');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (54,'Croatia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (55,'Cuba');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (56,'Cyprus');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (57,'Czech Republic');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (58,'Denmark');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (59,'Djibouti');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (60,'Dominica');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (61,'Dominican Republic');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (62,'East Timor');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (63,'Ecuador');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (64,'Egypt');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (65,'El Salvador');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (66,'Equatorial Guinea');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (67,'Eritrea');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (68,'Estonia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (69,'Ethiopia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (70,'External Territories of Australia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (71,'Falkland Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (72,'Faroe Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (73,'Fiji Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (74,'Finland');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (75,'France');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (76,'French Guiana');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (77,'French Polynesia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (78,'French Southern Territories');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (79,'Gabon');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (80,'Gambia The');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (81,'Georgia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (82,'Germany');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (83,'Ghana');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (84,'Gibraltar');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (85,'Greece');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (86,'Greenland');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (87,'Grenada');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (88,'Guadeloupe');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (89,'Guam');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (90,'Guatemala');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (91,'Guernsey and Alderney');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (92,'Guinea');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (93,'Guinea-Bissau');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (94,'Guyana');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (95,'Haiti');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (96,'Heard and McDonald Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (97,'Honduras');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (98,'Hong Kong S.A.R.');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (99,'Hungary');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (100,'Iceland');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (101,'India');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (102,'Indonesia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (103,'Iran');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (104,'Iraq');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (105,'Ireland');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (106,'Israel');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (107,'Italy');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (108,'Jamaica');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (109,'Japan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (110,'Jersey');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (111,'Jordan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (112,'Kazakhstan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (113,'Kenya');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (114,'Kiribati');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (115,'Korea North');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (116,'Korea South');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (117,'Kuwait');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (118,'Kyrgyzstan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (119,'Laos');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (120,'Latvia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (121,'Lebanon');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (122,'Lesotho');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (123,'Liberia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (124,'Libya');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (125,'Liechtenstein');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (126,'Lithuania');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (127,'Luxembourg');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (128,'Macau S.A.R.');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (129,'Macedonia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (130,'Madagascar');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (131,'Malawi');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (132,'Malaysia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (133,'Maldives');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (134,'Mali');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (135,'Malta');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (136,'Man (Isle of)');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (137,'Marshall Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (138,'Martinique');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (139,'Mauritania');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (140,'Mauritius');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (141,'Mayotte');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (142,'Mexico');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (143,'Micronesia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (144,'Moldova');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (145,'Monaco');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (146,'Mongolia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (147,'Montserrat');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (148,'Morocco');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (149,'Mozambique');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (150,'Myanmar');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (151,'Namibia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (152,'Nauru');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (153,'Nepal');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (154,'Netherlands Antilles');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (155,'Netherlands The');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (156,'New Caledonia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (157,'New Zealand');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (158,'Nicaragua');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (159,'Niger');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (160,'Nigeria');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (161,'Niue');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (162,'Norfolk Island');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (163,'Northern Mariana Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (164,'Norway');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (165,'Oman');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (166,'Pakistan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (167,'Palau');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (168,'Palestinian Territory Occupied');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (169,'Panama');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (170,'Papua new Guinea');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (171,'Paraguay');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (172,'Peru');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (173,'Philippines');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (174,'Pitcairn Island');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (175,'Poland');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (176,'Portugal');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (177,'Puerto Rico');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (178,'Qatar');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (179,'Reunion');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (180,'Romania');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (181,'Russia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (182,'Rwanda');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (183,'Saint Helena');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (184,'Saint Kitts And Nevis');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (185,'Saint Lucia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (186,'Saint Pierre and Miquelon');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (187,'Saint Vincent And The Grenadines');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (188,'Samoa');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (189,'San Marino');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (190,'Sao Tome and Principe');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (191,'Saudi Arabia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (192,'Senegal');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (193,'Serbia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (194,'Seychelles');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (195,'Sierra Leone');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (196,'Singapore');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (197,'Slovakia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (198,'Slovenia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (199,'Smaller Territories of the UK');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (200,'Solomon Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (201,'Somalia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (202,'South Africa');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (203,'South Georgia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (204,'South Sudan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (205,'Spain');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (206,'Sri Lanka');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (207,'Sudan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (208,'Suriname');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (209,'Svalbard And Jan Mayen Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (210,'Swaziland');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (211,'Sweden');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (212,'Switzerland');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (213,'Syria');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (214,'Taiwan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (215,'Tajikistan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (216,'Tanzania');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (217,'Thailand');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (218,'Togo');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (219,'Tokelau');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (220,'Tonga');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (221,'Trinidad And Tobago');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (222,'Tunisia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (223,'Turkey');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (224,'Turkmenistan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (225,'Turks And Caicos Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (226,'Tuvalu');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (227,'Uganda');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (228,'Ukraine');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (229,'United Arab Emirates');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (230,'United Kingdom');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (231,'United States');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (232,'United States Minor Outlying Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (233,'Uruguay');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (234,'Uzbekistan');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (235,'Vanuatu');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (236,'Vatican City State(Holy See)');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (237,'Venezuela');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (238,'Vietnam');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (239,'Virgin Islands (British)');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (240,'Virgin Islands(US)');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (241,'Wallis And Futuna Islands');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (242,'Western Sahara');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (243,'Yemen');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (244,'Yugoslavia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (245,'Zambia');
INSERT INTO  ofertas.pais (id_aut_pais , nombre) VALUES (246,'Zimbabwe');

COMMIT;