INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(1,'Agropecuario');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(2,'Alimentos');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(3,'Asegurador');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(4,'Bebidas y Tabaco');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(5,'Comercial');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(6,'Comercio al por Mayor');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(7,'Comercio al por Menor');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(8,'Construcción');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(9,'Consultorías/Asesorías');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(10,'Consumo Masivo');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(11,'Cuero y Calzado');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(12,'Editorial e Impresión');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(13,'Educativo');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(14,'Energético');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(15,'Entretenimiento');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(16,'Estatal y Relacionados');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(17,'Financiero');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(18,'Industrial');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(19,'Investigación');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(20,'Manufactura');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(21,'Medios');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(22,'Minería, Hierro, Acero y otros Materiales');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(23,'Naval');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(24,'Otra Actividad');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(25,'Plástico y Caucho');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(26,'Productos de Vidrio');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(27,'Publicidad y Mercadeo');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(28,'Pulpa, Papel y Cartón');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(29,'Químicos');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(30,'Salud');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(31,'Servicios');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(32,'Tecnología');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(33,'Telecomunicaciones');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(34,'Textiles, Prendas de Vestir y Calzado');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(35,'Transporte');
INSERT INTO ofertas.sectores(id_aut_sector, nombre) values(36,'Vehiculos y Partes');